services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__STORAGE__ON_DISK_PAYLOAD=true
      - QDRANT__STORAGE__WAL__WAL_CAPACITY_MB=64
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6333/livez || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  web:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    env_file:
      - ./server/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - DOCKER=true
      - PYTHONPATH=/app
    ports:
      - "8000:8000"  # changed from 8000 to 8001 to avoid conflicts
    depends_on:
      redis:
        condition: service_healthy
#      qdrant:
#        condition: service_healthy
    volumes:
      - ./server/media:/app/media  # for local file uploads if not using s3
#      - ./server/db.sqlite3:/app/db.sqlite3
      - ./server:/app
  celery:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: celery -A celery_app worker --loglevel=debug -E -Q ocr,embedding,validation,default
    env_file:
      - ./server/.env
    environment:
      - REDIS_URL=redis://redis:6380/0
      - QDRANT_URL=http://qdrant:6333
      - DOCKER=true
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
#      qdrant:
#        condition: service_healthy
    volumes:
      - ./server/media:/app/media  # share media files with web service
      - ./server:/app

volumes:
  redis_data:
  qdrant_data: